module.exports = {
  schema:  `
  type Book {
    title: String
    author: Author
  }

  type Author {
    name: String
  }

  type Query {
    books: [Book]
    authors: [Author]
  }
  `,
  resolvers: (model) => {
    return {
       Book: {
          author(book) {
            console.log('foobar', book.author['_id'], book.author) 
            return model.authors.findOne({'_id': book.author['_id']})
          }
        },
        Query: {
          books: () => model.books.find(),
          authors: () => model.authors.find(),
        }
    }
  }
} 
