module.exports = {
  schema:  `
  type Book {
    _id: String
    title: String
    author: Author
  }

  type Author {
    _id: String
    name: String
    address: Address
    books: [Book]
  }

  type Query {
    books: [Book]
    authors: [Author]
  }

  type Address {
    street: String
    city: String
  }
  `,
  resolvers: ({Author, Book}) => {
    return {
       Book: {
          author(book) {
            return Author.findById(book.author._id)
          }
        },
        Author: {
          books(author) {
            return Book.find({author: author._id})
          }
        },
        Query: {
          books: () => Book.find(),
          authors: () => Author.find(),
        }
    }
  }
} 
